textures_begin
    texture(enemy),
    texture(tile_dungeon),
    texture(tile_house),
    texture(font),
    texture(logo),
    texture(hand),
    texture(hud),
    texture(particle_fire),
    texture(particle_portal_easy),
    texture(collectible),
textures_end
